"""
Named Entity types for UMR annotation
"""

ne_types = [
    # Person types
    "person",
    "president",
    "officer",
    "police",
    "soldier",
    "athlete",
    "artist",
    "author",
    "doctor",
    "teacher",
    "student",
    "lawyer",
    "scientist",
    "politician",
    "engineer",
    "worker",
    "businessman",
    "entrepreneur",
    "leader",
    
    # Organization types
    "organization",
    "company",
    "corporation",
    "institution",
    "university",
    "school",
    "hospital",
    "government",
    "agency",
    "department",
    "party",
    "team",
    
    # Location types
    "location",
    "country",
    "city",
    "state",
    "province",
    "town",
    "village",
    "street",
    "address",
    "building",
    "region",
    "continent",
    "mountain",
    "river",
    "ocean",
    "lake",
    "desert",
    "forest",
    "park",
    
    # Time expressions
    "date-entity",
    "time",
    "year",
    "month",
    "day",
    "hour",
    "minute",
    "second",
    "decade",
    "century",
    "era",
    "season",
    
    # Quantity expressions
    "monetary-quantity",
    "mass-quantity",
    "distance-quantity",
    "volume-quantity",
    "temperature-quantity",
    "area-quantity",
    "duration-quantity",
    "frequency-quantity",
    "speed-quantity",
    
    # Other common entity types
    "product",
    "service",
    "event",
    "program",
    "project",
    "document",
    "publication",
    "book",
    "article",
    "website",
    "email",
    "phone",
    "account",
    "disease",
    "medicine",
    "vehicle",
    "device",
    "system",
    "software",
    "language",
    "concept",
    "idea",
    "theory",
    "law",
    "rule",
    "regulation",
    "policy"
] 