known_relations = {
    # :accompanier from AMR, maybe replaced by :companion in UMR?
    ':actor': {'type': 'participant', 'repeat': False},
    ':affectee': {'type': 'participant', 'repeat': False},
    ':age': {'type': 'modifier', 'repeat': False},
    ':apprehensive': {'type': 'modifier', 'repeat': False},
    ':ARG0': {'type': 'participant', 'repeat': False},
    ':ARG1': {'type': 'participant', 'repeat': False},
    ':ARG2': {'type': 'participant', 'repeat': False},
    ':ARG3': {'type': 'participant', 'repeat': False},
    ':ARG4': {'type': 'participant', 'repeat': False},
    ':ARG5': {'type': 'participant', 'repeat': False},
    ':ARG6': {'type': 'participant', 'repeat': False},
    ':aspect': {'type': 'attribute', 'repeat': False, 'values': ['habitual', 'generic', 'iterative', 'inceptive', 'imperfective', 'process', 'atelic-process', 'perfective', 'state', 'reversible-state', 'irreversible-state', 'inherent-state', 'point-state', 'activity', 'undirected-activity', 'directed-activity', 'endeavor', 'semelfactive', 'undirected-endeavor', 'directed-endeavor', 'performance', 'incremental-accomplishment', 'nonincremental-accomplishment', 'directed-achievement', 'reversible-directed-achievement', 'irreversible-directed-achievement']},
    ':beneficiary': {'type': 'participant', 'repeat': False}, #todo: affecttee
    ':calendar': {'type': 'modifier', 'repeat': False},
    ':cause': {'type': 'modifier', 'repeat': True},
    ':causer': {'type': 'participant', 'repeat': False},
    ':century': {'type': 'modifier', 'repeat': False},
    ':companion': {'type': 'participant', 'repeat': False},
    ':concession': {'type': 'modifier', 'repeat': True},
    ':condition': {'type': 'modifier', 'repeat': True},
    ':consist-of': {'type': 'modifier', 'repeat': False}, #todo:? split into other roles(have-group-91, have-material-91)
    ':day': {'type': 'attribute', 'repeat': False},
    ':dayperiod': {'type': 'attribute', 'repeat': False},
    ':decade': {'type': 'modifier', 'repeat': False},
    ':degree': {'type': 'attribute', 'repeat': False, 'value': ['intensifier', 'downtoner', 'equal']},
    ':destination': {'type': 'modifier', 'repeat': True}, #todo? :goal
    ':direction': {'type': 'modifier', 'repeat': True},
    ':domain': {'type': 'modifier', 'repeat': False}, #todo:? replaced with have-mode, have rel role, exist 91
    ':duration': {'type': 'modifier', 'repeat': True},
    ':era': {'type': 'modifier', 'repeat': False},
    ':example': {'type': 'modifier', 'repeat': True},
    ':experiencer': {'type': 'participant', 'repeat': False},
    ':extent': {'type': 'modifier', 'repeat': False},
    ':force': {'type': 'participant', 'repeat': False},
    ':frequency': {'type': 'modifier', 'repeat': False},
    ':goal': {'type': 'participant', 'repeat': False},
    ':group': {'type': 'modifier', 'repeat': False},
    ':instrument': {'type': 'participant', 'repeat': False},
    ':li': {'type': 'modifier', 'repeat': False}, #todo: is this replaced by :list-item
    #':location': {'type': 'modifier', 'repeat': True}, # obsolete; use :place instead
    ':manner': {'type': 'modifier', 'repeat': True},
    ':material': {'type': 'participant', 'repeat': False},
    ':medium': {'type': 'modifier', 'repeat': False},
    ':mod': {'type': 'modifier', 'repeat': True},
    ':modal-predicate': {'type': 'modifier', 'repeat': False}, # Note: The guidelines and the spreadsheet originally defined ':modpred' but it was changed to ':modal-predicate' in UMR 1.0 to make the annotation more human-readable.
    ':modal-strength': {'type': 'attribute', 'repeat': False, 'values': ['full-affirmative', 'partial-affirmative', 'neutral-affirmative', 'neutral-negative', 'partial-negative', 'full-negative']}, # Note: The guidelines and the spreadsheet originally defined ':modstr' but it was changed to ':modal-strength' in UMR 1.0 to make the annotation more human-readable.
    ':mode': {'type': 'attribute', 'repeat': False, 'values':['imperative', 'interrogative', 'expressive']},
    ':month': {'type': 'attribute', 'repeat': False},
    ':name': {'type': 'modifier', 'repeat': False},
    ':op1': {'type': 'attribute', 'repeat': False}, # There is no theoretical limit on the number after ':op'. When ':op2' or higher occurs, we will clone ':op1' on the fly.
    ':ord': {'type': 'modifier', 'repeat': False},
    ':other-role': {'type': 'modifier', 'repeat': True},
    ':part': {'type': 'modifier', 'repeat': True},
    ':path': {'type': 'modifier', 'repeat': True},
    ':place': {'type': 'participant', 'repeat': False},
    ':polarity': {'type': 'attribute', 'repeat': False, 'value':['-', 'umr-unknown', 'truth-value']},
    ':polite': {'type': 'attribute', 'repeat': False, 'values':['+']}, #todo:?
    ':possessor': {'type': 'modifier', 'repeat': True}, # Note: The guidelines originally defined ':poss' but it was changed to ':possessor' (the dependent node is the possessor of the parent). See also the spreadsheet.
    ':purpose': {'type': 'modifier', 'repeat': True},
    ':quant': {'type': 'attribute', 'repeat': False},
    ':quarter': {'type': 'modifier', 'repeat': False},
    ':quote': {'type': 'modifier', 'repeat': True}, # Note: The guidelines and the spreadsheet originally defined ':quot' but it was changed to ':quote' in UMR 1.0 to make the annotation more human-readable.
    ':reason': {'type': 'modifier', 'repeat': True},
    ':recipient': {'type': 'participant', 'repeat': False},
    ':refer-number': {'type': 'attribute', 'repeat': False, 'values': ['singular', 'non-singular', 'dual', 'paucal', 'plural', 'non-dual-paucal', 'greater-plural', 'trial', 'non-trial-paucal']}, # Note: The guidelines and the spreadsheet originally defined ':ref-number' but it was changed to ':refer-number' in UMR 1.0 to make the annotation more human-readable.
    ':refer-person': {'type': 'attribute', 'repeat': False, 'values': ['1st', '2nd', '3rd', '4th', 'non-3rd', 'non-1st', 'excl','incl']}, # Note: The guidelines and the spreadsheet originally defined ':ref-person' but it was changed to ':refer-person' in UMR 1.0 to make the annotation more human-readable.
    ':refer-definiteness':{'type':'attribute', 'repeat': False, 'values': ['class']}, #todo: for cases pronouns that are generic. "you don't do this"
    ':scale': {'type': 'modifier', 'repeat': False},
    ':source': {'type': 'participant', 'repeat': False},
    ':start': {'type': 'participant', 'repeat': False},
    ':stimulus': {'type': 'participant', 'repeat': False},
    ':subevent': {'type': 'modifier', 'repeat': False},
    ':substitute': {'type': 'modifier', 'repeat': False},
    ':subtraction': {'type': 'modifier', 'repeat': False},
    ':temporal': {'type': 'modifier', 'repeat': True},
    ':theme': {'type': 'participant', 'repeat': False},
    ':time': {'type': 'attribute', 'repeat': True},
    ':timezone': {'type': 'modifier', 'repeat': False},
    ':topic': {'type': 'modifier', 'repeat': False},
    ':undergoer': {'type': 'participant', 'repeat': False},
    ':unit': {'type': 'attribute', 'repeat': False},
    ':value': {'type': 'attribute', 'repeat': False},
    ':vocative': {'type': 'modifier', 'repeat': False},
    ':weekday': {'type': 'modifier', 'repeat': False},
    ':wiki': {'type': 'attribute', 'repeat': False},
    ':year': {'type': 'attribute', 'repeat': False},
    ':year2': {'type': 'attribute', 'repeat': False},
    # We added the following relations that are not in the guidelines:
    ':according-to': {'type': 'modifier', 'repeat': False}, # child node is the source of the information #todo:? say-91
    ':axis-relative-polarities': {'type': 'attribute', 'repeat': False, 'values':['left-handed', 'right-handed']},
    ':framework-type':{'type':'attribute', 'repeat':False, 'values':['absolute', 'intrinsic','relative']},
    ':anchor-framework-translation': {'type': 'attribute', 'repeat': False, 'values': ['rotated', 'reflected']},
    ':co-actor': {'type': 'modifier', 'repeat': False},
    ':axis': {'type': 'modifier', 'repeat': False},
    ':anchor': {'type': 'modifier', 'repeat': False},
    ':color': {'type': 'modifier', 'repeat': False},
    ':concessive-condition': {'type': 'modifier', 'repeat': False},
    ':role': {'type': 'modifier', 'repeat': False},
    ':identity': {'type': 'modifier', 'repeat': False},
    ':orientation': {'type': 'modifier', 'repeat': False},
    ':result': {'type': 'modifier', 'repeat': False},
    ':size': {'type': 'modifier', 'repeat': False},
    ':list-item': {'type': 'modifier', 'repeat': False},
    ':configuration': {'type': 'modifier', 'repeat': False},
    ':pure-addition': {'type': 'modifier', 'repeat': False}
}

discourse_concepts = [
    # This have :sntN children
    'multi-sentence',
    # These have :opN children:
    'and', 'or', 'inclusive-disjunction', 'exclusive-disjunction', 'and-but', 'consecutive', 'additive', 'and-unexpected', 'and-contrast',
    # These are rolesets and have :ARGN children:
    'but-91', 'unexpected-co-occurrence-91', 'contrast-91',
    # These are reifications, thus rolesets, and have :ARGN children:
    'have-apprehensive-91', 'have-condition-91', 'have-pure-addition-91', 'have-substitution-91', 'have-concession-91', 'have-concessive-condition-91', 'have-subtraction-91'
]

abstract_concepts = {
    'person': {'type': 'basic', 'sub-roles': [':ref-person', ':ref-number']},
    'individual-person': {'type': 'basic', 'sub-roles': [':ref-person', ':ref-number']}, #todo: bert says replacing 'person'? just the named entities
    'place': {'type': 'basic', 'sub-roles': [':ref-person', ':ref-number']}, #todo: what does ref menu mean?
    'event': {'type': 'basic', 'sub-roles': [':ref-person', ':ref-number']}, #todo: what does ref menu mean?
    'name': {'type': 'basic', 'sub-roles': ':opN'},
    'umr-choice': {'type': 'basic', 'sub-roles': ':opN'},
    'manner': {'type': 'basic', 'sub-roles': []},# [] means these have no suggested sub-roles
    'umr-unknown': {'type': 'basic', 'sub-roles': []},  # [] means these have no suggested sub-roles
    'umr-unintelligible': {'type': 'basic', 'sub-roles': []},  # [] means these have no suggested sub-roles
    'umr-empty': {'type': 'basic', 'sub-roles': []},  # [] means these have no suggested sub-roles

    'date-entity':{'type': 'entities', 'sub-roles':[':calendar', ':century', ':day', ':dayperiod', ':decade',':era',':month',':quarter', ':season',':time', ':timezone', ':weekday', ':year', ':year2']},
    'string-entity':{'type':'entities', 'sub-roles':[':value']},
    'ordinal-entity': {'type': 'entities', 'sub-roles': [':value', ':range',':range-start', 'range-trajectory']},
    'url-entity': {'type': 'entities', 'sub-roles': [':value']},
    'percentage-entity': {'type': 'entities', 'sub-roles': [':value']},
    'phone-number-entity': {'type': 'entities', 'sub-roles': [':value']},
    'email-address-entity': {'type': 'entities', 'sub-roles': [':value']},
    'score-entity': {'type': 'entities', 'sub-roles': ':opN'},

    'date-interval': {'type': 'other', 'sub-roles': [':op1',':op2']},
    'value-interval': {'type': 'other', 'sub-roles': [':op1', ':op2']},
    'between': {'type': 'other', 'sub-roles': [':op1', ':op2', ':op3']},
    'slash': {'type': 'other', 'sub-roles': [':op1', ':op2']},
    'emoticon': {'type': 'other', 'sub-roles': [':value']},
    'relative-position': {'type': 'other', 'sub-roles': [':op1', ':quant', ':direction']},

    'less-than': {'type': 'math', 'sub-roles': [':op1']},
    'more-than': {'type': 'math', 'sub-roles': [':op1']},
    'at-least': {'type': 'math', 'sub-roles': [':op1']},
    'at-most': {'type': 'math', 'sub-roles': [':op1']},
    'sum-of': {'type': 'math', 'sub-roles': ':opN'},
    'product-of': {'type': 'math', 'sub-roles': ':opN'},
    'ratio-of': {'type': 'math', 'sub-roles': ':opN'},
    'difference-of': {'type': 'math', 'sub-roles': ':opN'},
    'quotient-of': {'type': 'math', 'sub-roles': ':opN'},
    'power-of': {'type': 'math', 'sub-roles': [':op1', ':op2']},
    'root-of': {'type': 'math', 'sub-roles': [':op1', ':op2']},
    'logarithm-of': {'type': 'math', 'sub-roles': [':op1', ':op2']},

    'monetary-quantity': {'type': 'quantities', 'sub-roles': [':quant', ':unit']},
    'distance-quantity': {'type': 'quantities', 'sub-roles': [':quant', ':unit']},
    'area-quantity': {'type': 'quantities', 'sub-roles': [':quant', ':unit']},
    'volume-quantity': {'type': 'quantities', 'sub-roles': [':quant', ':unit']},
    'temporal-quantity': {'type': 'quantities', 'sub-roles': [':quant', ':unit']},
    'frequency-quantity': {'type': 'quantities', 'sub-roles': [':quant', ':unit']},
    'speed-quantity': {'type': 'quantities', 'sub-roles': [':quant', ':unit']},
    'acceleration-quantity': {'type': 'quantities', 'sub-roles': [':quant', ':unit']},
    'mass-quantity': {'type': 'quantities', 'sub-roles': [':quant', ':unit']},
    'force-quantity': {'type': 'quantities', 'sub-roles': [':quant', ':unit']},
    'pressure-quantity': {'type': 'quantities', 'sub-roles': [':quant', ':unit']},
    'energy-quantity': {'type': 'quantities', 'sub-roles': [':quant', ':unit']},
    'power-quantity': {'type': 'quantities', 'sub-roles': [':quant', ':unit']},
    'charge-quantity': {'type': 'quantities', 'sub-roles': [':quant', ':unit']},
    'potential-quantity': {'type': 'quantities', 'sub-roles': [':quant', ':unit']},
    'resistance-quantity': {'type': 'quantities', 'sub-roles': [':quant', ':unit']},
    'inductance-quantity': {'type': 'quantities', 'sub-roles': [':quant', ':unit']},
    'magnetic-field-quantity': {'type': 'quantities', 'sub-roles': [':quant', ':unit']},
    'magnetic-flux-quantity': {'type': 'quantities', 'sub-roles': [':quant', ':unit']},
    'radiation-quantity': {'type': 'quantities', 'sub-roles': [':quant', ':unit']},
    'fuel-consumption-quantity': {'type': 'quantities', 'sub-roles': [':quant', ':unit']},
    'numerical-quantity': {'type': 'quantities', 'sub-roles': [':quant', ':unit']},
    'information-quantity': {'type': 'quantities', 'sub-roles': [':quant', ':unit']},
    'concentration-quantity': {'type': 'quantities', 'sub-roles': [':quant', ':unit']},
    'catalytic-activity-quantity': {'type': 'quantities', 'sub-roles': [':quant', ':unit']},
    'acidity-quantity': {'type': 'quantities', 'sub-roles': [':quant', ':unit']},
    'seismic-quantity': {'type': 'quantities', 'sub-roles': [':quant', ':unit']},
    'temperature-quantity': {'type': 'quantities', 'sub-roles': [':quant', ':unit']},
    'angle-quantity': {'type': 'quantities', 'sub-roles': [':quant', ':unit']},

    'armiture': {'type': 'spatial-abstract-concepts', 'sub-roles': [':axis-relative-polarities', ':framework-type', ':anchor-framework-translation']},
    'relative-orientation': {'type': 'spatial-abstract-concepts',
                 'sub-roles': [':orientation-of', ':op1', ':quant', ':orientation', ':axis']},
    'cartesian-coordinate-entity': {'type': 'spatial-abstract-concepts',
                 'sub-roles': [':x', ':y', ':z',':framework']},
    'dimension-entity': {'type': 'spatial-abstract-concepts',
                 'sub-roles': [':value', ':unit']},
    'slope-quantity': {'type': 'spatial-abstract-concepts',
                 'sub-roles': [':quant', ':rise-axis', ':run-axis']},
    'composite-entity': {'type': 'spatial-abstract-concepts',
                 'sub-roles': []},
    'space': {'type': 'spatial-abstract-concepts',
                         'sub-roles': []},
    'trajectory': {'type': 'spatial-abstract-concepts',
                         'sub-roles': []}
}

ne_types = ['academic-organization',
 'aircraft',
 'aircraft-type',
 'airport',
 'amino-acid',
 'animal',
 'animal-nest',
 'armed-organization',
 'assembly',
 'association',
 'automobile',
 'automobile-type',
 'autonomous-region / nation?',
 'avalanche',
 'bay',
 'behavior',
 'biomedical-entity',
 'body-of-literature',
 'book',
 'breed',
 'bridge',
 'broadcast-network',
 'broadcast-program',
 'building',
 'business',
 'canal',
 'canyon',
 'category',
 'celestial-entity',
 'cell',
 'cell-line',
 'ceremony',
 'chemical-compound',
 'chemical-element',
 'city-square',
 'clan',
 'coastland',
 'color',
 'company',
 'computer-program',
 'conceptualization',
 'constellation',
 'continent',
 'country',
 'country-partition',
 'country-region',
 'court-decision',
 'criminal-organization',
 'cultural-activity',
 'cultural-artifact',
 'cultural-facility',
 'culturally-protected-area',
 'currency-system',
 'cyber-entity',
 'cyberattack',
 'cyclone',
 'dam',
 'dance',
 'degree',
 'desert',
 'diet',
 'disease',
 'dna-sequence',
 'duststorm',
 'earthquake',
 'ecosystem',
 'enzyme',
 'ethnic-group',
 'event',
 'facility',
 'family',
 'festival',
 'financial-entity',
 'fire',
 'flood',
 'food-dish',
 'forest',
 'galaxy',
 'game',
 'gene',
 'geo-political-entity',
 'geographical-entity',
 'glaciological-entity',
 'government-organization',
 'government-output',
 'grassland',
 'gulf',
 'historical-period',
 'honor',
 'hotel',
 'human-settlement',
 'identification-number',
 'incident',
 'international-organization',
 'island',
 'journal',
 'lake',
 'land-entity',
 'landslide',
 'language',
 'legislation',
 'local-region',
  'macro-molecular-complex',
 'magazine',
 'market',
 'market-sector',
 'measurement-system',
 'medical-condition',
 'medicinal-substance',
 'mission',
 'molecular-physical-entity',
 'moon',
 'mountain',
 'mountain-range',
 'movement',
 'museum',
 'music',
 'music-key',
 'musical-note',
 'name',
 'nationality',
 'natural-disaster',
 'natural-object',
 'natural-reserve',
 'news-media',
 'notational-system',
 'nucleic-acid',
 'ocean',
 'organization',
 'palace',
 'park',
 'pass',
 'pathogen',
 'pathway',
 'peninsula',
 'performance',
 'performing-group',
 'person',
 'place',
 'planet',
 'plant',
 'policy',
 'political-ideology',
 'political-organization',
 'port',
 'principle',
 'product',
 'protected-area',
 'protein',
 'protein-family',
 'protein-segment',
 'publication',
 'qualification',
 'railway-line',
 'region',
 'regional-group',
 'religion',
 'religious-group',
 'religious-organization',
 'river',
 'road',
 'rock',
 'room',
 'sea',
 'ship',
 'ship-type',
 'small-celestial-body',
 'small-molecule',
 'social-group',
 'social-media',
 'social-program',
 'solar-system',
 'spacecraft',
 'spacecraft-type',
 'spaceport',
 'species',
 'sports-facility',
 'sports-organization',
 'star',
 'station',
 'strait',
 'system',
 'tax',
 'taxon',
 'test',
 'theater',
 'therapy',
 'thing',
 'thoroughfare',
 'treaty',
 'tunnel',
 'unit',
 'utility-structure',
 'valley',
 'variable',
 'vehicle',
 'vehicle-type',
 'volcanic-disaster',
 'volcano',
 'war',
 'water-entity',
 'weapon',
 'weapon-type',
 'website',
 'wetland',
 'work-of-art',
 'world-region',
 'worship-place',
 'writing-script']

non_event_rolesets = [
    'have-actor-91', 'have-co-actor-91', 'have-undergoer-91', 'have-theme-91', 'have-force-91', 'have-causer-91',
    'have-companion-91', 'have-affectee-91', 'have-recipient-91', 'have-temporal-91', 'have-instrument-91',
    'have-manner-91', 'have-place-91', 'have-direction-91', 'have-path-91', 'have-goal-91', 'have-start-91',
    'have-source-91', 'have-extent-91', 'have-quant-91', 'have-degree-92', 'have-frequency-91', 'have-duration-91',
    'have-purpose-91', 'have-cause-91', 'have-reason-91', 'have-part-91', 'have-group-91', 'have-material-91',
    'have-topic-91', 'have-vocative-91', 'have-medium-91', 'have-age-91', 'have-example-91', 'have-mod-91',
    'have-other-role-91', 'have-ord-91', 'have-name-91', 'have-value-91', 'have-unit-91', 'have-polarity-91',
    'have-modal-strength-91', 'have-list-item-91', 'have-mode-91', 'be-polite-91', 'have-91', 'have-experience-91',
    'have-result-91', 'have-configuration-91', 'have-orientation-91',

    'have-size-91', 'have-color-91', 'have-configuration-91', 'have-orientation-91', 'cartesian-framework-91',
    'spatial-sequence-91', 'have-anchor-91', 'have-axis-91',

    'have-91', 'belong-91', 'exist-91', 'have-place-91', 'have-mod-91', 'have-role-91', 'have-rel-role-92', 'have-org-role-92',
    'identity-91',

    'byline-91', 'cite-91', 'correlate-91', 'course-91', 'distribution-range-91', 'have-degree-91',
    'hyperlink-91', 'include-91', 'infer-91', 'publication-91', 'reference-illustration-91', 'resemble-91',
    'rate-entity-91', 'score-on-scale-91', 'statistical-test-91',
    'street-address-91', 'mean-91', 'have-experience-91', 'weather-91', 'range-91', 'gesture-91',
    'emit-sound-91', 'proverb-91', 'say-91'
]

doc_level_relations = {"temporal": [':contained', ':before', ':after', ':overlap', ':depends-on'],
                      "modal":[':modal', ':full-affirmative', ':partial-affirmative', ':strong-partial-affirmative', ':weak-partial-affirmative', ':neutral-affirmative', ':strong-neutral-affirmative', ':weak-neutral-affirmative', ':full-negative', ':partial-negative', ':strong-partial-negative', ':weak-partial-negative', ':neutral-negative', ':strong-neutral-negative', ':weak-neutral-negative', ':unspecified'],
                      "coref":[':same-entity', ':same-event', ':subset-of']}

doc_level_rolesets = {"temporal": ['document-creation-time', 'past-reference', 'present-reference', 'future-reference'],
                      "modal": ['root', 'author', 'null-conceiver'],
                      "coref":[]}
