"""empty message

Revision ID: 70a3fb9fee18
Revises: 2f9a7de2e565
Create Date: 2023-06-30 12:29:10.490068

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '70a3fb9fee18'
down_revision = '2f9a7de2e565'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('docda', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sent_annot', sa.Text(), nullable=False, server_default='{}'))
        batch_op.add_column(sa.Column('doc_annot', sa.Text(), nullable=False, server_default='{}'))
        batch_op.add_column(sa.Column('sent_umr', sa.JSON(), server_default='{}', nullable=False))
        batch_op.add_column(sa.Column('doc_umr', sa.JSON(), server_default='{}', nullable=False))
        batch_op.add_column(sa.Column('actions', postgresql.ARRAY(sa.Text()), server_default='{}', nullable=False))
        batch_op.add_column(sa.Column('alignment', sa.JSON(), server_default='{}', nullable=False))
        batch_op.add_column(sa.Column('sent_id', sa.Integer(), nullable=False, server_default='0'))

    # with op.batch_alter_table('docqc', schema=None) as batch_op:
    #     batch_op.alter_column('qc_user_id',
    #            existing_type=sa.INTEGER(),
    #            nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('docqc', schema=None) as batch_op:
        batch_op.alter_column('qc_user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('docda', schema=None) as batch_op:
        batch_op.drop_column('sent_id')
        batch_op.drop_column('alignment')
        batch_op.drop_column('actions')
        batch_op.drop_column('doc_umr')
        batch_op.drop_column('sent_umr')
        batch_op.drop_column('doc_annot')
        batch_op.drop_column('sent_annot')

    # ### end Alembic commands ###
