"""empty message

Revision ID: 2f8862802688
Revises: 70a3fb9fee18
Create Date: 2023-07-18 14:07:36.302781

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f8862802688'
down_revision = '70a3fb9fee18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # with op.batch_alter_table('docqc', schema=None) as batch_op:
    #     batch_op.alter_column('qc_user_id',
    #            existing_type=sa.INTEGER(),
    #            nullable=False)

    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('visibility', sa.Boolean()), nullable=False, server_default=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_column('visibility')

    with op.batch_alter_table('docqc', schema=None) as batch_op:
        batch_op.alter_column('qc_user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
