"""empty message

Revision ID: 2f9a7de2e565
Revises: f4ef8bf8da86
Create Date: 2023-06-28 14:18:30.159153

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f9a7de2e565'
down_revision = 'f4ef8bf8da86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('docqc', schema=None) as batch_op:
        batch_op.add_column(sa.Column('qc_user_id', sa.Integer()))
        batch_op.alter_column('sent_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.create_foreign_key(None, 'user', ['qc_user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('docqc', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('sent_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('qc_user_id')

    # ### end Alembic commands ###
