"""empty message

Revision ID: bf51de7f3d84
Revises: 2f8862802688
Create Date: 2023-07-18 14:34:13.390187

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import expression

# revision identifiers, used by Alembic.
revision = 'bf51de7f3d84'
down_revision = '2f8862802688'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # with op.batch_alter_table('docqc', schema=None) as batch_op:
    #     batch_op.alter_column('qc_user_id',
    #            existing_type=sa.INTEGER(),
    #            nullable=False)


    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('visibility', sa.Boolean(), nullable=False, server_default=expression.false()))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.alter_column('visibility',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    with op.batch_alter_table('docqc', schema=None) as batch_op:
        batch_op.alter_column('qc_user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
