"""empty message

Revision ID: c5750399c32b
Revises: 
Create Date: 2023-06-26 15:33:30.467736

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5750399c32b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('test_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('doc', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'project', ['project_id'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    with op.batch_alter_table('projectuser', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])
        batch_op.create_foreign_key(None, 'project', ['project_id'], ['id'])

    with op.batch_alter_table('sent', schema=None) as batch_op:
        batch_op.alter_column('doc_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=40),
               type_=sa.String(length=200),
               existing_nullable=False)

    # ### end Alembic commands ###
constraint_name = "fk_projectuser_user_id"

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=40),
               existing_nullable=False)

    with op.batch_alter_table('sent', schema=None) as batch_op:
        batch_op.alter_column('doc_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('projectuser', schema=None) as batch_op:
        batch_op.drop_constraint(constraint_name, type_='foreignkey')
        batch_op.drop_constraint(constraint_name, type_='foreignkey')

    with op.batch_alter_table('doc', schema=None) as batch_op:
        batch_op.drop_constraint(constraint_name, type_='foreignkey')
        batch_op.drop_constraint(constraint_name, type_='foreignkey')

    op.drop_table('test')
    # ### end Alembic commands ###
