"""empty message

Revision ID: f4ef8bf8da86
Revises: c5750399c32b
Create Date: 2023-06-27 14:32:24.259433

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f4ef8bf8da86'
down_revision = 'c5750399c32b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('test_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('docqc', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sent_annot', sa.Text(), server_default='{}', nullable=False))
        batch_op.add_column(sa.Column('doc_annot', sa.Text(), server_default='{}', nullable=False))
        batch_op.add_column(sa.Column('sent_umr', sa.JSON(), server_default='{}', nullable=False))
        batch_op.add_column(sa.Column('doc_umr', sa.JSON(), server_default='{}', nullable=False))
        batch_op.add_column(sa.Column('actions', postgresql.ARRAY(sa.Text()), server_default='{}', nullable=False))
        batch_op.add_column(sa.Column('alignment', sa.JSON(), server_default='{}', nullable=False))
        batch_op.add_column(sa.Column('sent_id', sa.Integer()))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('docqc', schema=None) as batch_op:
        batch_op.drop_column('sent_id')
        batch_op.drop_column('alignment')
        batch_op.drop_column('actions')
        batch_op.drop_column('doc_umr')
        batch_op.drop_column('sent_umr')
        batch_op.drop_column('doc_annot')
        batch_op.drop_column('sent_annot')

    op.drop_table('test')
    # ### end Alembic commands ###
